### ISSUE TITLE
A bunch of messages "Skipping "../.emacs.d/init.d/*, it's already loaded."

### ISSUE THREAD

**Issue by EDmitry** [edvorg/emacs-configs#3]
When using a similar configuration I am getting a bunch of messages in a format of:

```
Skipping /Users/dgorbik/.emacs.d/init.d/objc, it's already loaded.
```

For every file in `init.d` I have. Is that a bug of `load-dir-one` or is that normal?

**Comment by edvorg** [comment]
It look like load-dir-one bug
