### ISSUE TITLE
load-dir doesn't play nicely with .dir-locals.el

### ISSUE THREAD

**Issue by ivan-m** [edvorg/emacs-configs#5]
In this configuration you use the `load-dir` package to avoid having to manually `require` every file.

However, after trying this myself, it seems that `load-dir` will also try to load any `.dir-locals.el` files in the specified directory, which causes problems when it refers to variables/functions that haven't been found yet as those packages aren't loaded.

It might be worth documenting this.

**Comment by edvorg** [comment]
Hi, thank you for your issue. This problem could probably avoided by load-dir configuration. Will check on this matter when I get a chance.

**Comment by ivan-m** [comment]
The maintainers of load-dir have updated it to be able to ignore certain files (like `.dir-locals.el`, which is specified by default).

As such, this is working for me now.

**Comment by edvorg** [comment]
Cool, thank you!
