### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mkrupcale** [edvorg/emacs-configs#7]
These configurations serve as a good example of how to work with your `req-package` system, and it would be nice to be able to use them freely. As it stands, they are all unlicensed and therefore fully copyright protected[1]. It would be preferable if they were licensed under a permissive license such as the MIT/Expat license.

[1] https://blog.codinghorror.com/pick-a-license-any-license/

**Comment by edvorg** [comment]
Hi. I'm sorry for the late response. I think I'll update the project with the LGPL license. Would this solve your problem?

**Comment by mkrupcale** [comment]
Hello, thanks for the response. I think licensing as LGPL would solve the problem and certainly would be an improvement over the current unlicensed status.

**Comment by edvorg** [comment]
Fixed @mkrupcale Enjoy =)
